name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.1.1

      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        deploy-repo: xiaodeaux/xiaodeaux.github.io
